title: dot86
description: wip.
url: https://oAGoulart.github.io/dot86
remote_theme: oAGoulart/lesta
#theme: lesta
baseurl: /dot86
plugins:
  - jekyll-seo-tag

exclude: [
  Gemfile.lock,
  lesta.gemspec,
  README.md,
  CHANGELOG.md,
  Gemfile, vendor, scripts
]
